### ISSUE TITLE
Uncaught TypeError: Cannot read property 'for-tag-list' of undefined

### ISSUE THREAD

**Issue by tibbon** [kbparagua/numerous.js#1]
Using your example, I cannot get it to work with JQuery 1.7.1 in Rails 3. I'm getting the error of "Uncaught TypeError: Cannot read property 'for-tag-list' of undefined" in Chrome's debug. It points to line 24 as having the issue. Something about the form[this.id] being undefined. 

<%= content_for :head do %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/themes/base/jquery-ui.css", :id => "theme" %>
  <%= javascript_include_tag "http://ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js" %>
    <%= javascript_include_tag "numerous.js" %>
<% end %>

<%= form_for @broadcast do |form| %>

  Tags:
  <div id="tag-list"></div>

  <div class="numerous">
    <div class="numerous-form">
      <%= form.fields_for :broadcast, Broadcast.new, :child_index => "replace_this" do |f| %>
        <%= f.text_field :name %>
        <%= f.hidden_field :_destroy, :value => 0, :class => "numerous-remove-field" %>
        <%= link_to "delete", "#", :class => "numerous-remove" %>
      <% end %>
    </div>

```
<%= link_to "add tag", "#", :class => "numerous-add", :id => "for-tag-list" %>
```

  </div>
<% end %>

**Comment by kbparagua** [comment]
Yo tibbon!

Thank you for using numerous.js
It seems that you forgot to put the fields_for and the add-tag inside `<div class="numerous"></div>` tag, and you must put the fields_for inside `<div class="numerous-form"></div>`.

Please see Usage and Conventions. Thanks.
